### ISSUE TITLE
[Bug] Server down per UW

### ISSUE THREAD

**Issue by evantrillium** [Trillium-Solutions/oba_rvtd_deployer#5]
https://trilliumtransit.zendesk.com/agent/tickets/58736

---------- Forwarded message ---------
From: Alan Borning <borning@cs.washington.edu>
Date: Thu, Jan 13, 2022 at 6:24 PM
Subject: Re: OneBusAway Feedback
To: Connie Lynn <lynn1@jeffnet.org>
Cc: <iphone-app@onebusaway.org>

Thanks for the report and sorry about the trouble.  It looks like the OneBusAway server for RVTD is down -- I will let them know.  Once they get the server back up, your OneBusAway app should just start working again.  (You don't need to do anything to the app.)
   regards,
   Alan Borning

On Thu, Jan 13, 2022 at 4:44 PM Connie Lynn <lynn1@jeffnet.org> wrote:
How can we help? Please enter your response below:

My recent stops do not appear with the next bus coming. It says data is missing. Please fix. Thank you, Connie Lynn

The following information is provided for troubleshooting purposes. If you are uncomfortable sharing any of the following information you may remove it, however it may affect our ability to assist you.

App Version = 21.7.2
OS Version = 15.1
Locale = en
VoiceOver Running = false
Bookmark Count = 0
Registered for Notifications = true
Location Authorization = authorizedWhenInUse
Current Location = (42.18480514306442,-122.69112444823136)
Region = Rogue Valley, Oregon
Region ID = 9
Base API URL = https://oba.rvtd.org/onebusaway-api-webapp/
Device = iPhone10,4

Sent from my iPhone

@ed-g @schurnsi

**Comment by lisaattrillium** [comment]
@ed-g can you take a look at this?

**Comment by schurnsi** [comment]
What it looks like to click on a bus stop this morning for RVTD in OBA for iOS. In case it helps.

Should note that Sean at RVTD did mention that Engie was going to tweak something in their real-time feed for service alerts this week. So not sure if the change is having a system wide effect now.

@evantrillium who is Connie Lynn?

![IMG_1050](https://user-images.githubusercontent.com/7635869/149554201-52859146-76a2-4fff-badb-d534c0c7bd0b.PNG)

![IMG_1049](https://user-images.githubusercontent.com/7635869/149554215-2746f0ea-316b-4008-8dd3-eb2274105677.PNG)

**Comment by evantrillium** [comment]
@schurnsi no idea who Connie Lynn is.

@schurnsi charge your phone this is giving me an anxiety attack

**Comment by ed-g** [comment]
@arr0nax  there is a web monitor set up but it's not alerting. 

Would you fix using zabbix best practice & test both before and after an ansible zabbix playbook run?

https://zabbix.trilliumtransit.com/zabbix/httpconf.php?form=update&hostid=10374&httptestid=1245

**Comment by ed-g** [comment]
Hmm, the monitor might be OK.

Uptime robot monitor also works and gets correct data.

https://uptimerobot.com/dashboard#784479207

http://oba.rvtd.org:8080/onebusaway-webapp/where/standard/stop.action?id=981_610030

@evantrillium according to monitoring and to my testing the server is running just fine. Test stop succeeds.

Can they please provide more specific information in their request? We cannot reproduce using the information they've provided.

**Comment by ed-g** [comment]
![image](https://user-images.githubusercontent.com/2495118/149579234-21c0bb47-fea7-4d2d-b372-73c1aeebbdff.png)

**Comment by evantrillium** [comment]
@ed-g thank you for the confirmation - I will punt back to the agency and ask they review any issues with Engie at this time if there is still an issue (it may be resolved)

**Comment by ed-g** [comment]
Pls assign back to me if they have more information until then ball is in their court.

**Comment by evantrillium** [comment]
update

----

As a test we removed the GTFS alert from the Engie system.

Matt Christensen
Technology Services Manager
Rogue Valley Transportation District
541-842-2094


On Fri, Jan 14, 2022 at 1:19 PM Christensen, Matt <mchristensen@rvtd.org> wrote:
It appears to be working on my Android device.
Maybe it's just an iOS issue?


Matt Christensen
Technology Services Manager
Rogue Valley Transportation District
541-842-2094

**Comment by evantrillium** [comment]
@ed-g I cannot assign/add labels to this repo

**Comment by ed-g** [comment]
I'm sorry it's not working for him but unless they can do a more detailed report than than "it doesn't work on my phone" I can't act on it.

We need at a minimum the stop ID, and ideally the link to the oba web page like I provided above http://oba.rvtd.org:8080/onebusaway-webapp/where/standard/stop.action?id=981_610030

**Comment by schurnsi** [comment]
@ed-g Alan from University of Washington and Sean Barbeau University of South Florida jumped into this issue again this morning. 

Their suggestions in a nutshell are:
1. the alerts or an alert is getting cached in the OBA server
2. can we restart the server to see if it clears the alert?
3. can we delete the XML file in the root directory to see if that clears the alert?

Can you review what was thrown back and forth this morning and let me know if of it "rings true" and if anything can be done on our side to test these theories?

--Seth

**iOS and Cached Alerts:**

The REST API endpoint is returning the alert. I do not have the URL with me right now, but the test alert was present when I curl the endpoint. Please see attached image/screenshot. 

The iOS app does not store alerts. Even if it did, it wouldn’t have saved the test alert since it couldn’t parse it in the first place. 

— alan C, iOS

![image](https://user-images.githubusercontent.com/7635869/150185505-c1264bf9-1b15-4ff1-9526-38d7496e7c16.png)







**Cached Alert:**

OBA Android doesn’t cache any alerts, it will only display what is retrieved live from the REST API when you tap on a stop. You can see that the alert is still live in the RVTD API response using this request URL:https://oba.rvtd.org/onebusaway-api-webapp/api/where/arrivals-and-departures-for-stop/981_270290.json?minutesAfter=65&app_ver=126&key=v1_BktoDJ2gJlu6nLM6LsT9H8IUbWc%3DcGF1bGN3YXR0c0BnbWFpbC5jb20%3D "situationIds": ["981_Test 4 - System Wide Alert"],…situations": [{"activeWindows": [{"from": 1641283200,"to": 1672905600}],"allAffects": [{"agencyId": "","applicationId": "","directionId": "","routeId": "981_14484","stopId": "","tripId": ""},{"agencyId": "","applicationId": "","directionId": "","routeId": "981_14139","stopId": "","tripId": ""},{"agencyId": "","applicationId": "","directionId": "","routeId": "981_12503","stopId": "","tripId": ""},{"agencyId": "","applicationId": "","directionId": "","routeId": "981_12505","stopId": "","tripId": ""},{"agencyId": "","applicationId": "","directionId": "","routeId": "981_12499","stopId": "","tripId": ""},{"agencyId": "","applicationId": "","directionId": "","routeId": "981_12501","stopId": "","tripId": ""},{"agencyId": "","applicationId": "","directionId": "","routeId": "981_12502","stopId": "","tripId": ""},{"agencyId": "","applicationId": "","directionId": "","routeId": "981_13523","stopId": "","tripId": ""},{"agencyId": "","applicationId": "","directionId": "","routeId": "981_14483","stopId": "","tripId": ""},{"agencyId": "","applicationId": "","directionId": "","routeId": "981_14690","stopId": "","tripId": ""},{"agencyId": "","applicationId": "","directionId": "","routeId": "981_12507","stopId": "","tripId": ""},{"agencyId": "","applicationId": "","directionId": "","routeId": "981_12506","stopId": "","tripId": ""},{"agencyId": "","applicationId": "","directionId": "","routeId": "981_12504","stopId": "","tripId": ""},{"agencyId": "","applicationId": "","directionId": "","routeId": "981_12500","stopId": "","tripId": ""}],"consequences": [],"creationTime": 1642196083536,"description": null,"id": "981_Test 4 - System Wide Alert","publicationWindows": [],"reason": "","severity": "","summary": null,"url": null}], I believe there is a cache in OBA server for alerts, though – I remember this being an issue previously, so even if the GTFS-RT feed doesn’t have the alert the OBA server might still be retaining it. I don’t recall exactly how this works, restarting the server should get rid of it. | Sean Barbeau was not explicitly added to the ticket by the requester or an agent. Learn more | Private note
-- | -- | --
Sean Barbeau was not explicitly added to the ticket by the requester or an agent. Learn more
Private note



**XML Suggestion:**

As a possible alternative to restarting the server – depending on the version of OBA server you’re running, IIRC alerts are stored in an XML file in the root directory of where the server is running. Make a backup of the file first in case things go south, but you could try deleting that XML file to see if that removes the cached alert.
